<a href="https://colab.research.google.com/github/akbhagaw/numpy/blob/main/numpy_practice_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
# Numapy Practice

In [67]:
import numpy as np
import pandas as pd

######## Create one D array
one_d = np.array([1,2,3,4,5])
print(one_d)


[1 2 3 4 5]


In [68]:
####### Create two D array
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [69]:
###### Create three D array
three_d = np.array([[[2,4,6,8],[5,6,7,9]],[[5,6,8,4],[4,5,6,8]]])
print(three_d)
np.ndim(three_d)

[[[2 4 6 8]
  [5 6 7 9]]

 [[5 6 8 4]
  [4 5 6 8]]]


3

In [70]:
np.shape(three_d)
three_d.shape

(2, 2, 4)

In [71]:
np.size(three_d)

16

In [72]:
np.all(three_d)

np.True_

In [73]:
np.amax(three_d, axis=0) # Returned a Max value of an array

array([[5, 6, 8, 8],
       [5, 6, 7, 9]])

In [74]:
np.amax(three_d, axis=1 ) # Returned a Max value of an array

array([[5, 6, 7, 9],
       [5, 6, 8, 8]])

In [75]:
three_d = np.array([[[9,4,6,8],[5,6,7,9]],[[5,6,8,10],[4,5,6,8]]])
print(three_d)

[[[ 9  4  6  8]
  [ 5  6  7  9]]

 [[ 5  6  8 10]
  [ 4  5  6  8]]]


In [76]:
max_column= np.amax(three_d, axis=1 )
print(max_column)

[[ 9  6  7  9]
 [ 5  6  8 10]]


In [77]:
max_row= np.amax(two_d, axis=1 ) # its provided Max value of array axis=1 (Rows)
print(max_row)

[5 6]


In [78]:
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [79]:
max_column= np.amax(two_d, axis=0 ) # its provided Max value of array axis=0 (Columns)
print(max_column)

[3 5 6 5]


In [80]:
np.amin(two_d, axis=0) # its provided Min value of array axis=0 (Columns)

array([2, 3, 4, 4])

In [81]:
np.amin(two_d, axis=1) # its provided Max value of array axis=1 (Rows)

array([2, 3])

In [82]:
np.shape(two_d) # its provide shape (number_row, number_column)

(2, 4)

In [83]:
# another way to check it
two_d.shape # provide the same resulte (number_row, number_column)

(2, 4)

In [84]:
# use arange to create one D, Two D and three D array
np.arange((5)) # One_D array


array([0, 1, 2, 3, 4])

In [85]:
np.arange(5) # One_D array

array([0, 1, 2, 3, 4])

In [86]:
arr_1= np.arange(10,50,5)
two_d_arr = np.array(arr_1)
two_d_arr.reshape(2,4)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [87]:
three_d= two_d_arr.reshape(2, 2, 2) # 3D array create
three_d

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]]])

In [88]:
np.ndim(three_d) # display dimentions

3

In [89]:
zero_20_range= np.arange(1, 19).astype(dtype=np.int32)
zero_20_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18], dtype=int32)

In [90]:
zero_20_range.size

18

In [93]:
two_3_arr = zero_20_range.reshape(3,6)
two_3_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]], dtype=int32)

In [97]:
matrixA = zero_20_range[0:9].reshape(3,3)
matrixB = zero_20_range[9:19].reshape(3,3)
sum_of_matrix = matrixA+matrixB
sum_of_matrix

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]], dtype=int32)

In [98]:
matrixA = zero_20_range[0:9].reshape(3,3)
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [99]:
matrixB = zero_20_range[9:19].reshape(3,3)
matrixB

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int32)

In [100]:
multiply_matrix= matrixA * matrixB # two Matrics multiply
multiply_matrix

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]], dtype=int32)

In [102]:
divide_matrix= matrixA // matrixB # two Matrics divide
divide_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)