<a href="https://colab.research.google.com/github/akbhagaw/numpy/blob/main/numpy_practice_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
# Numapy Practice

In [66]:
import numpy as np
import pandas as pd

######## Create one D array
one_d = np.array([1,2,3,4,5])
print(one_d)


[1 2 3 4 5]


In [67]:
####### Create two D array
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [68]:
###### Create three D array
three_d = np.array([[[2,4,6,8],[5,6,7,9]],[[5,6,8,4],[4,5,6,8]]])
print(three_d)
np.ndim(three_d)

[[[2 4 6 8]
  [5 6 7 9]]

 [[5 6 8 4]
  [4 5 6 8]]]


3

In [69]:
np.shape(three_d)
three_d.shape

(2, 2, 4)

In [70]:
np.size(three_d)

16

In [71]:
np.all(three_d)

np.True_

In [72]:
np.amax(three_d, axis=0) # Returned a Max value of an array

array([[5, 6, 8, 8],
       [5, 6, 7, 9]])

In [73]:
np.amax(three_d, axis=1 ) # Returned a Max value of an array

array([[5, 6, 7, 9],
       [5, 6, 8, 8]])

In [74]:
three_d = np.array([[[9,4,6,8],[5,6,7,9]],[[5,6,8,10],[4,5,6,8]]])
print(three_d)

[[[ 9  4  6  8]
  [ 5  6  7  9]]

 [[ 5  6  8 10]
  [ 4  5  6  8]]]


In [75]:
max_column= np.amax(three_d, axis=1 )
print(max_column)

[[ 9  6  7  9]
 [ 5  6  8 10]]


In [76]:
max_row= np.amax(two_d, axis=1 ) # its provided Max value of array axis=1 (Rows)
print(max_row)

[5 6]


In [77]:
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [78]:
max_column= np.amax(two_d, axis=0 ) # its provided Max value of array axis=0 (Columns)
print(max_column)

[3 5 6 5]


In [79]:
np.amin(two_d, axis=0) # its provided Min value of array axis=0 (Columns)

array([2, 3, 4, 4])

In [80]:
np.amin(two_d, axis=1) # its provided Max value of array axis=1 (Rows)

array([2, 3])

In [81]:
np.shape(two_d) # its provide shape (number_row, number_column)

(2, 4)

In [82]:
# another way to check it
two_d.shape # provide the same resulte (number_row, number_column)

(2, 4)

In [84]:
# use arange to create one D, Two D and three D array
np.arange((5)) # One_D array


array([0, 1, 2, 3, 4])

In [85]:
np.arange(5) # One_D array

array([0, 1, 2, 3, 4])

In [107]:
arr_1= np.arange(10,50,5)
two_d_arr = np.array(arr_1)
two_d_arr.reshape(2,4)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])