<a href="https://colab.research.google.com/github/akbhagaw/numpy/blob/main/numpy_practice_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numapy Practice

In [ ]:
import numpy as np
import pandas as pd

######## Create one D array
one_d = np.array([1,2,3,4,5])
print(one_d)


[1 2 3 4 5]


In [ ]:
####### Create two D array
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [ ]:
###### Create three D array
three_d = np.array([[[2,4,6,8],[5,6,7,9]],[[5,6,8,4],[4,5,6,8]]])
print(three_d)
np.ndim(three_d)

[[[2 4 6 8]
  [5 6 7 9]]

 [[5 6 8 4]
  [4 5 6 8]]]


3

In [ ]:
np.shape(three_d)
three_d.shape

(2, 2, 4)

In [ ]:
np.size(three_d)

16

In [ ]:
np.all(three_d)

np.True_

In [ ]:
np.amax(three_d, axis=0) # Returned a Max value of an array

array([[5, 6, 8, 8],
       [5, 6, 7, 9]])

In [ ]:
np.amax(three_d, axis=1 ) # Returned a Max value of an array

array([[5, 6, 7, 9],
       [5, 6, 8, 8]])

In [ ]:
three_d = np.array([[[9,4,6,8],[5,6,7,9]],[[5,6,8,10],[4,5,6,8]]])
print(three_d)

[[[ 9  4  6  8]
  [ 5  6  7  9]]

 [[ 5  6  8 10]
  [ 4  5  6  8]]]


In [ ]:
max_column= np.amax(three_d, axis=1 )
print(max_column)

[[ 9  6  7  9]
 [ 5  6  8 10]]


In [ ]:
max_row= np.amax(two_d, axis=1 ) # its provided Max value of array axis=1 (Rows)
print(max_row)

[5 6]


In [ ]:
two_d = np.array([[2,3,4,5],[3,5,6,4]])
print(two_d)

[[2 3 4 5]
 [3 5 6 4]]


In [ ]:
max_column= np.amax(two_d, axis=0 ) # its provided Max value of array axis=0 (Columns)
print(max_column)

[3 5 6 5]


In [ ]:
np.amin(two_d, axis=0)

array([2, 3, 4, 4])

In [ ]:
np.amin(two_d, axis=1)

array([2, 3])